ALTER TABLE creator_profiles
  ADD COLUMN IF NOT EXISTS payout_method VARCHAR(40) NULL,
  ADD COLUMN IF NOT EXISTS payout_account_name VARCHAR(160) NULL,
  ADD COLUMN IF NOT EXISTS payout_bank_name VARCHAR(160) NULL,
  ADD COLUMN IF NOT EXISTS payout_account_encrypted TEXT NULL,
  ADD COLUMN IF NOT EXISTS payout_account_last4 CHAR(4) NULL,
  ADD COLUMN IF NOT EXISTS payout_ifsc VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS payout_upi_id VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS payout_email VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS payout_updated_at TIMESTAMP NULL;